### ISSUE TITLE
[NM] Strong encryption is not properly configured via `pia -a`

### ISSUE THREAD

**Issue by max-baz** [flamusdiu/python-pia#12] opened 2016-07-28 22:27 UTC
Install the `aur/private-internet-access-vpn-dev` package.

Put the following configuration in `/etc/private-internet-access/pia.conf`:

```
[pia]
openvpn_auto_login = True
strong_encryption = True

[configure]
apps = nm
hosts = France
```

Run `sudo pia -a`, then look at the file `/etc/NetworkManager/system-connections/France`:
1. `port=1198`, but should be `port=1197`.
2. `cipher=aes-128-cbc`, but should be `cipher=AES-256-CBC` (case is irrelevant for the connection, but GUI of NetworkManager understands only capitalized version, so better use capitalized).
3. `auth=SHA256` is missing.

With the configuration generated by `pia` the connection is not even being established. When I manually make the adjustments named above, everything works as expected.

---

Small things to improve, irrelevant for the primary issue:
- When installing `aur/private-internet-access-vpn-dev`, the installation ends with the following (though everything works afterwards):

```
:: Running post-transaction hooks...
(1/2) Updating manpage index...
(2/2) Updating VPN configuations...
error: unable to run hook pia-install.hook: could not satisfy dependencies
```
- When running `sudo pia -a`, the following is printed:

```
WARNING Strong encryption enabled! Ignoring manual cipher settings!
WARNING Strong encryption enabled! Ignoring manual cipher settings!
WARNING Strong encryption enables! Ignoring manual authentication settings!
```

Note the first message is duplicated, and note the typo in the word "enabled" in the last line.

**Comment by flamusdiu** [comment] 2016-07-28 23:50
Thanks! I will look at it. The duplicate message is due to setting both OpenVPN and NM configs. I need to probably check that outside the loop.

**Comment by flamusdiu** [comment] 2016-08-01 01:20
`error: unable to run hook pia-install.hook: could not satisfy dependencies`

I don't know why this error is happening. I am just going to remove the hooks. I don't get the error when I install. =(

**Comment by max-baz** [comment] 2016-08-01 01:24
Sure, that's not a big deal, it's OK to run `pia -a` manually after installation.
Most important job is to produce the correct configuration file, with all the adjustments that I mentioned :wink:

**Comment by flamusdiu** [comment] 2016-08-01 01:29
@maximbaz yeah, I changed the cause due to how it looks in the file. Conman but NM seems to have some issues with that -- go figure. lol

**Comment by flamusdiu** [comment] 2016-09-19 19:48
@maximbaz is this still an issue?

**Comment by max-baz** [comment] 2016-09-19 20:25
@flamusdiu I've just installed the most recent `aur/private-internet-access-vpn-dev` and all the issues described are still reproducible, except for this error is not happening anymore: `error: unable to run hook pia-install.hook: could not satisfy dependencies`.

But most importantly, the `port`, `cipher` and `auth` are still wrong in the generated file. All the other reported issues are small and not really relevant to the case.

**Comment by flamusdiu** [comment] 2016-09-19 21:36
can you post a config file, plz?

**Comment by max-baz** [comment] 2016-09-19 21:55
@flamusdiu it is posted in the first message of this issue. I'm using exactly these steps and configs.

**Comment by max-baz** [comment] 2016-09-19 21:57
But frankly there aren't any new commits in `dev` or `master` branches since I originally reported this issue, so no wonder it is still reproducing for me. Perhaps you simply forgot to do `git push`, @flamusdiu? :smile:

**Comment by flamusdiu** [comment] 2016-09-19 22:09
@maximbaz well, then, I swear, I need some reading glasses or something. For some reason, I thought it was only the hooks causing issues, so I'll update the dev branch tonight or tomorrow and let you know.

**Comment by flamusdiu** [comment] 2016-09-25 12:43
@maximbaz just add some changes to the dev branch can you try that for me please?

**Comment by max-baz** [comment] 2016-09-25 12:56
@flamusdiu sure, but the new commit https://github.com/flamusdiu/python-pia/commit/96f712ae46950101bb5b4a0709c51a6cc59a5921 in dev branch has 0 changes. Maybe merge went wrong?

**Comment by flamusdiu** [comment] 2016-09-25 13:09
Yeah, I amended the previous comment but for some reason my local git branch said it was out of date and merged a blank comment. Let me see about removing that a sec.

**Comment by flamusdiu** [comment] 2016-09-25 13:10
Removed the empty comment. =D

**Comment by flamusdiu** [comment] 2016-09-25 13:11
I am going to test on my box for conman. I already updated the AUR package ( https://aur.archlinux.org/packages/private-internet-access-vpn-dev/) as well.

**Comment by max-baz** [comment] 2016-09-25 13:18
`port` is still `1198`, but should be `1197`.
`cipher` is now capitalized, but the value is `AES-128-CBC`, while it should be `AES-256-CBC`.
`auth` is now not missing, but has wrong value of `SHA1`, while it should be `SHA256`.

**Comment by flamusdiu** [comment] 2016-09-25 13:19
oops ... dammit. one sec. I was about to check the port when mine failed =P

**Comment by flamusdiu** [comment] 2016-09-25 13:50
Now rebuild it again.

**Comment by flamusdiu** [comment] 2016-09-25 13:54
For some reason Conman is being dumb:

```
default via 192.168.xx.1 dev enp2s0 
10.xx.xx.x via 10.xx.xx.x dev vpn0 
```

Keeps by-passing the VPN.

**Comment by flamusdiu** [comment] 2016-09-25 14:13
Okay. restarted `connman-vpn` and now it's working properly.

**Comment by max-baz** [comment] 2016-09-25 14:14
@flamusdiu now it looks good on NM as well, and nothing seems to be bypassing.
Thanks for the fix! I guess you can close this issue.

**Comment by flamusdiu** [comment] 2016-09-25 14:20
@maximbaz let me merge it to the master branch and get that setup. I'll close when we can both test it. Thanks for the support! Sorry for the delay on fixing it.

**Comment by max-baz** [comment] 2016-09-25 14:32
Sounds good. Let me know when AUR package is updated, and I will run the tests again.

**Comment by flamusdiu** [comment] 2016-09-25 14:41
updated now

**Comment by max-baz** [comment] 2016-09-25 14:50
`aur/private-internet-access-vpn` works flawlessly, it can configure both "normal" and "strong" configurations.

Thanks once again @flamusdiu!

**Comment by flamusdiu** [comment] 2016-09-25 14:52
Thanks for the testing. Just push a minor update for the PKGBUILD. Let's hope there isn't any more issues. lol

**Closed as completed by flamusdiu** 2016-09-25 14:52 UTC
Labels: bug
